name: django-celery-app Deploy to AWS ec2

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  APPLICATION_NAME: django-app
  DEPLOYMENT_GROUP_WEB: django-web-dg
  DEPLOYMENT_GROUP_CELERY: django-celery-dg
  S3_BUCKET: django-artifact-731049002337-ap-south-1-an
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Update deployment timestamp
      run: |
        echo "// Updating timestamp for deployment on $(date)"

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role-${{ github.run_id }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Verify Identity
      run: aws sts get-caller-identity
    
    - name: Create Deployment Artifact
      run: |
        zip -r app.zip . \
        -x "*.git*" \
          "venv/*" \
          "__pycache__/*" \
          "*.pyc"
    
    - name: Upload to S3
      run: |
        aws s3 cp app.zip s3://django-artifact-731049002337-ap-south-1-an/app.zip
    
    - name: Deploy to Web ASG
      run: |
        aws deploy create-deployment \
          --application-name $APPLICATION_NAME \
          --deployment-group-name $DEPLOYMENT_GROUP_WEB \
          --s3-location bucket=${{ env.S3_BUCKET }},key=app.zip,bundleType=zip
    
    - name: Deploy to Celery ASG
      run: |
        aws deploy create-deployment \
          --application-name $APPLICATION_NAME \
          --deployment-group-name $DEPLOYMENT_GROUP_CELERY \
          --s3-location bucket=${{ env.S3_BUCKET }},key=app.zip,bundleType=zip
